### ISSUE TITLE
혹시라도 조금이라도 도움이 될까해서 오타 이슈 걸어 봅니다.

### ISSUE THREAD

**Issue by chandong83** [golbin/TensorFlow-Tutorials#1]
안녕하세요.
제공해주시는 내용 잘 보고 있습니다. ^^
감사합니다.

혹시라도 조금이라도 도움이 될까해서 오타 이슈걸어 봅니다.

README.md
-자연어 분석에 **매주** 중요하게 사용되는 Word2Vec 모델을 간단하게 구현해봅니다.
+자연어 분석에  **매우** 중요하게 사용되는 Word2Vec 모델을 간단하게 구현해봅니다.

앞으로도 좋은 내용 잘 부탁드립니다.

**Comment by golbin** [comment]
감사합니다!! 👍
