### ISSUE TITLE
[2-3 word2vec] tf.nn.nce_loss 함수 파라미터

### ISSUE THREAD

**Issue by HayunJin** [golbin/TensorFlow-Tutorials#12]
덕분에 많이 공부하고 있습니다! 2-3 word2vec 예제에서 수정사항이 있습니다. 텐서플로우 라이브러리가 업데이트 되면서 nce_loss 함수의 파라미터가 바뀌었습니다!
https://github.com/tensorflow/tensorflow/commit/761b12ed82d31195de002cdd687cbb77d7aba628
를 참고하세요~

**Comment by golbin** [comment]
감사합니다. 확인해보겠습니다!

**Comment by golbin** [comment]
확인해보니 이미 수정된 내용이네요. 감사합니다. (_ _)
