### ISSUE TITLE
TensorFlow-Tutorials/08 - RNN/ChatBot/model/

### ISSUE THREAD

**Issue by dvmoomoodv** [golbin/TensorFlow-Tutorials#14]
golbin님 소스로 처음 입문하여 공부하고 있는 개발자입니다. 
챗봇부분 작업하다가 model 부분에 학습결과물이 있어 바로 시작하는데 에러가 자꾸 나서요. 
지워보고 다시 학습을 해보았더니 잘 되더라구요. 

에러 내용을 텍스트 첨부합니다. 

어떤 이유때문에 그런건지 잘 모르겠어서 질문드립니다. 

[error.txt](https://github.com/golbin/TensorFlow-Tutorials/files/1076315/error.txt)

**Comment by golbin** [comment]
저장되어 있는 모델이 수정하기 전의 코드로 학습된 모델이어서 그렇습니다.

피드백 감사드립니다.

**Comment by dvmoomoodv** [comment]
답변 감사합니다. golbin님
