### ISSUE TITLE
about 11 . inception

### ISSUE THREAD

**Issue by turkeyB** [golbin/TensorFlow-Tutorials#17]
Very interesting tutorial indeed. Thanks a lot.

i tried the code in 11.inception and i found that i can run a code like this 

` import tensorflow as tf
 hello = tf.constant('hello,tensor!')
 sess = tf.Session()
 print(sess.run(hello))
hello,tensor!`
but when i insert your .py file like retrain.py and predict.py into /tensorflow folder, and run the code you listed above like this
`# python retrain.py \
    --bottleneck_dir=./workspace/bottlenecks \
    --model_dir=./workspace/inception \
    --output_graph=./workspace/flowers_graph.pb \
    --output_labels=./workspace/flowers_labels.txt \
    --image_dir ./workspace/flower_photos \
    --how_many_training_steps 1000`
it suggests that
 `Traceback (most recent call last):
  File "retrain.py", line 81, in <module>
    from tensorflow.python.framework import graph_util
ImportError: cannot import name graph_util`
and i dont know how to do next...
Any comment on what I do wrong.
many thanks
Eric

**Comment by golbin** [comment]
Hi, What's your TensorFlow version?

**Comment by turkeyB** [comment]
it is 1.3.0
After I asked this question, I rebuilt tensorflow by scource and finally solved the problem. your tutorial is fabulous , thx anyway
