### ISSUE TITLE
Chatbot 문의사항

### ISSUE THREAD

**Issue by sunghwan523** [golbin/TensorFlow-Tutorials#19]
Chatbot 안드로이드 테스트용 app을 만들어 볼려고 하는데 .ckpt->.pb을 생성하는데 어떻게 진행해야할지 몰라서 이렇게 글을 남깁니다.

일반적으로 ckpt-.> pb 를 만들 때 bazel을 이용하여 생성하는 거 같았습니다. 그리고 마지막에 output에 예언값을 넣는 거 같은데. chatbot에서 train.py에 함수를 따라가서 model.py에서 summary가 최종 예언값으로 생각되어 넣어보니 bazel이 되지 않아서 이렇게 글을 남깁니다.
pb생성하면 안드로이드에 올리는 거는 크게 무리가 없는 거 같은데... 이 부분에서 계속 막힙니다..

혹시 해보신 분이 있거나 도움을 주실수 있는 분을 도움 부탁드립니다. 감사합니다.

아래 사이트를 바탕으로 개발중입니다.
chatbot : https://github.com/golbin/TensorFlow-Tutorials/tree/master/10%20-%20RNN/ChatBot
ckpt->pb : 
1)http://blog.naver.com/PostView.nhn?blogId=cenodim&logNo=220967993466&parentCategoryNo=&categoryNo=12&viewDate=&isShowPopularPosts=true&from=search
2)http://gusrb.tistory.com/21

**Comment by golbin** [comment]
먼저, 현재 Chatbot 부분은 업데이트 된 지 오래되어 작동이 잘 안될 수 있습니다.

output 부분은 모델의 build_model 에 있는 self.outputs 부분인데, 이름이 정해져있지 않아 텐서를 출력해보고 설정하시면 됩니다.

또는, 이름을 정하시고 다시 학습시킨 뒤 사용하시면 됩니다.
