### ISSUE TITLE
Deep Q-network 최고 성능

### ISSUE THREAD

**Issue by hunkim** [golbin/TensorFlow-Tutorials#2]
DQN 예제를 찾다 보니 만들어 주신 게임이 간단하고 재미있어서 제가 수업에 사용하는 코드에 넣어서 돌려보는 중입니다. (픽셀을 넣어서 해보는 예제들은 정말 시간이 오래 걸리네요.)  제 구현에 버그가 없는지 계속 보는 중인데 혹시 이곳에 있는 DQN코드는 대략 어느정도 최고 성능이 나는지요? 한시간 정도 학습하셨다 하셨는데, 그때 total game의 수와 Avg Reward가 얼마정도 되었는지요?

코드 잘 보고 갑니다.

**Comment by golbin** [comment]
안녕하세요.

텐서보드에 몇가지 수치를 출력할 수 있는 코드는 간단하게 넣어두긴 했는데, 성능 관련해서는 측정해 본 바가 없어서 잘 모르겠습니다. ^^;

다만 한시간 정도 후에 리워드가 최고 수치가 되었고, 이후 거의 달라지지 않았었던 것만 기억나네요. ^^;
