### ISSUE TITLE
TensorFlow 1.4 로 업데이트 or branch

### ISSUE THREAD

**Issue by softgearko** [golbin/TensorFlow-Tutorials#21]
책 잘 보고 있습니다. 이해가 쉽게 잘 씌여진것 같아요. 
그런데, pip3로 텐서플로우를 설치하니 1.4.0이 설치 되는 군요.
예제소스들은 1.2용으로 작성된 것으로 알고 있는데요.  1.4용으로 업데이트 계획이 있으신지요?
1.2용도 필요할 것 같으니, 1.4용 브랜치를 만들어 관리하시면 좋을 것 같아요.

**Comment by golbin** [comment]
이 레포의 소스들은 텐서플로의 가장 기본적인 API들로만 구현하였습니다.

따라서 1.2, 1.3과 1.4에서 모두 잘 돌아갈 것 입니다.

혹시 문제가 생기면 알려주세요.

감사합니다.
