### ISSUE TITLE
책의 그림4-2, 그림10-4

### ISSUE THREAD

**Issue by softgearko** [golbin/TensorFlow-Tutorials#23]
"골빈해커의 3분 딥러닝" 책 아주 잘 보고 있습니다. 
책 피드백을 여기다 하는 것이 적절하지 않다면 다른 곳을 알려주세요.

그림4-2 실제 뉴런과 인공 뉴런
활성화함수 동작은 세포체 내에서 이루어지는 것으로 알고 있습니다. 가지돌기에서 입력x를 받고, 그것에 가중치를 곱하고 바이어스를 더하는 부분역시 기지돌기와 신경세포체 내의 활동으로 알고 있습니다. http://cs231n.github.io/neural-networks-1/ 에 그렇게 표현되어 있구요.
물론 잘 알고 계시고 이해 쉽게 그리기 위해 그린것 같은데  독자로서는 자칫 잘못 이해할 수 있을 것 같아서 의견 보냅니다.

그림10-4 단어 자동완성 RNN 모델
펼쳐진 LSTM 셀의 출력들이 마치 모두 xW+b에 들어가는 것처럼 표현되어 있는데요. 정확하게는 마지막 LSTM출력만 들어가게 되는 것이 맞다고 생각됩니다.

**Comment by golbin** [comment]
안녕하세요. 피드백 이쪽으로 남겨주셔도 좋습니다. ^^

그림4-2는 말씀하신대로 완전히 정확한 표현은 아니지만, 책의 목적을 개념적인 이해 정도의 수준을 쉽게 하기 위해 그렇게 표현했습니다. 말씀하신대로 혼동이 있을 수 있으니 고민해보도록 하겠습니다.

그림4-10은 말씀하신 것 처럼 오류가 맞네요. 수정할 수 있도록 하겠습니다. 알려주셔서 감사합니다. (_ _)

감사합니다.

**Comment by golbin** [comment]
잘 아시겠지만.. 10-4의 그림은 다음처럼 되어야해요. (검은부분이 없어져야)
