### ISSUE TITLE
DQN agent.py 실행시 그림이 안 나오는데요.

### ISSUE THREAD

**Issue by softgearko** [golbin/TensorFlow-Tutorials#26]
python3 agent.py --train
4500회까지 학습하다 Ctrl-C로 중단

python3 agent.py
실행하면, 컬러 상자 그림이 나와야 할 것 같은데, 다음 첨부 그림처럼 빈 상태로 숫자값만  바뀝니다.
![dqn_agent_nodraw](https://user-images.githubusercontent.com/525186/34244554-2b66d1cc-e669-11e7-98e0-c1358550cc24.PNG)

그림이 나오도록 하려면 어떻게 해야 할까요?

**Comment by golbin** [comment]
이슈를 늦게 보았네요.

`game.py` 코드 중 76번 줄의 self.axis.clear() 코드를 지우면 해결되며, 코드 반영해두었습니다.
