### ISSUE TITLE
Chapter 6 MNIST import error

### ISSUE THREAD

**Issue by battlerhythm** [golbin/TensorFlow-Tutorials#29]
아래와 같이 import하면,
![screen shot 2017-12-27 at 3 28 00 pm](https://user-images.githubusercontent.com/16344965/34392518-9e1be396-eb1a-11e7-8b13-15d5254835d4.png)

아래와 같은 에러 메세지가 나옵니다.
![screen shot 2017-12-27 at 3 28 15 pm](https://user-images.githubusercontent.com/16344965/34392541-ba1a7170-eb1a-11e7-8b7e-77aeee098c4a.png)

구글 미러서버에 문제가 생긴걸까요? ㅠㅠ

**Comment by golbin** [comment]
파이썬 최신버전으로 재설치를 하시거나, virtualenv 등으로 환경을 따로 만드시기 바랍니다.
