### ISSUE TITLE
튜토리얼 정말 감사합니다!

### ISSUE THREAD

**Issue by wonchul-kim** [golbin/TensorFlow-Tutorials#3]
안녕하세요, 튜토리얼 정말 감사하게 공부하고 잇습니다.

저는 RL을 공부하기 위해 dqn에 대한 튜토리얼을 보고 있는데,
저의 환경은 python2의 ipython notebook으로 하고 있어서 그런지,
어떻게든 셋팅해서 돌리고는 있는데,
다음 파일에서 모델을 읽는 중입니다. .. model/dqn.ckpt-140000
Avg.  ~~
~~~~~~~~~~~~~

라고 계속나오고,  그위에 네모칸의 시뮬레이션 칸만 나오고 다른 장애물과 자동차의 빨강, 파랑 등의 네모는 나오지 않네요.ㅜ.ㅜ.ㅜ.ㅜ.ㅜ.

학습을 시키고 나서 그 모델로 테스틑를 하는데 있어서 어떻게 진행되는지 여쭈고 싶습니다. 
모델을 읽고 나서 게임 진행을 볼 수 있는 건가요?
아니면 모델을 읽으면서 볼 수 있나요...?

**Comment by golbin** [comment]
실시간 업데이트 코드가 있어서 해당 코드의 결과는 ipython notebook 으로 하시면 안나올거고요. 다른 에디터나 터미널, 커맨드라인 창 등에서 직접 실행하셔야 애니메이션을 보실 수 있을겁니다.

notebook 에서 돌리시려면 출력 관련된 코드를 따로 넣어주셔야할겁니다. 이 부분은 제가 해보지 않아서 잘 모르겠네요.
