### ISSUE TITLE
혹시 책을 리디북스로 내실 계획은 없으신가요

### ISSUE THREAD

**Issue by kingsj0405** [golbin/TensorFlow-Tutorials#36]
컴퓨터 화면에 띄워놓고 읽고 싶네요 👍

**Comment by rycont** [comment]
저도 교보 이북으로 살까 했는데 DRM이라는 무시무시한 괴물때문에 그냥 종이책으로 샀어요ㅠㅠ 리디 이북으로 내주시면 다시 살 의향 있습니다!!

**Comment by jihwanahn** [comment]
[https://ridibooks.com/v2/Detail?id=443000530&_s=search&_q=%EA%B3%A8%EB%B9%88](url)
요거 아닌가용

**Comment by rycont** [comment]
헉 있었군요!! 종이책을 지금 반품하고 리디로 사야겠습니다...ㄷㄷㄷ 감사합니다!!!

**Comment by kingsj0405** [comment]
헉 왜 저 때는 검색이 안 됬을까요 반성하겠습니다
