### ISSUE TITLE
혹시 코딩환경을 여쭤봐도 될까요?

### ISSUE THREAD

**Issue by wonchul-kim** [golbin/TensorFlow-Tutorials#4]
저는 jupyter notebook으로 하는데,,,

올려주신 동영상처럼 smoooth하게 움직이지 않고

더 끊기네요....

cmd 창에서 띄어서 해도 마찬가지로 끊겨서요... 

혹시 해결 방법이 있을까요?

**Comment by golbin** [comment]
저는 jupyter notebook 을 사용하지 않고 직접 커맨드라인(터미널, cmd 등)에서 실행하였습니다.

프레임이 끊기는 것은 단순히 컴퓨터 속도가 느려서 그럴 수도 있는 등 여러가지 이유가 있을 것이라서, 환경을 상세하게 알지 못하면 파악하기 어렵습니다.

**Comment by wonchul-kim** [comment]
파이선 2.7이고, GPU서버 컴퓨터를 따로 사용하고 있습니다. 
(스펙은 자세히 모르지만, 연구실에서 구비한 것이기 때문에 성능이 딸리지는 않을 것 같습니다.)
jupyter를 사용하여 코드를 돌리면 비쥬얼라이제이션이 다르기 때문에 돌리지는 못하였고,

받은 코드를 그대로 cmd창에서 출력하였습니다. 
그리고 이떄에 끊기는 현상이 있어서요..ㅜ.ㅜ..

혹시 어떤 환경에서 작업하시는지 여쭤봐도 될까요?

**Comment by golbin** [comment]
문서에 있는 것 처럼 Python 2.7/TensorFlow 0.12 로 테스트 하였고, 맥과 윈도우에서 양쪽에서 돌려보았는데 문제 없었습니다.

어느부분 때문에 느려지는지 코드에 프로파일링용 코드를 삽입해서 확인해보시면 좋을 것 같네요.

**Comment by wonchul-kim** [comment]
답변 감사합니다!!
