### ISSUE TITLE
ValueError 해결 문의

### ISSUE THREAD

**Issue by kyutae** [golbin/TensorFlow-Tutorials#9]
안녕하세요.
좋은 예제 감사합니다.
저는 window10에서 Tensorflow 1.0, Python3.5 로 실행해보고 있는데,
아래와 같은 Error가 뜹니다.
random.randrange안의 변수가 정수가 아니라는 뜻인것 같은데,
어떻게 수정해야될지 몰라서 문의 드립니다. Python3.5라서 나오는 Error같긴한데, 제가 해결을 못하겠어서요.

  File "D:\TensorFlow-Tutorials-master\07 - DQN\game.py", line 104, in reset
    self.block[0]["col"] = random.randrange(self.road_left, self.road_right + 1)
  File "C:\toolkits\Python\Python35\lib\random.py", line 182, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()

**Comment by golbin** [comment]
안녕하세요. 본 소스는 TensorFlow 0.12, Python 2.7 에서 테스트 하였습니다. Python 3 에서는,

```python
self.block[0]["col"] = random.randrange(int(self.road_left), int(self.road_right + 1))
```

정도로 처리하시면 될 것 같습니다.

각종 파이썬 함수들은 다음 레퍼런스를 참조하세요. https://docs.python.org/3/library/functions.html
